---
title: "Cluster Averages for High Significance Genes"
author: "Mervin M Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float: true
---

# Purpose

We plot isoform-level expression for genes with wide-range of significance across 
clusters.

# Initialization

## Libraries
```{r libs, message=FALSE, warning=FALSE}
library(magrittr)
library(tidyverse)
library(Matrix)
library(matrixStats)
library(SingleCellExperiment)
library(Gviz)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(plyranges)
```

## Parameters
```{r set_params}
set.seed(20210818)

options(ucscChromosomeNames=FALSE)
BIN_WIDTH=50

txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

FILE_SE="data/se/kd6_essential_bulk_expressed.Rds"
FILE_GTF="../hcl/data/gff/utrome.e30.t5.gc39.pas3.f0.9999.w500.gtf.gz"
FILE_CLUSTERS="tbl/df_target_nnclusters_kd6_essential_ui10.csv"

LBL_UTR_CLUSTERS=c(
    "14"="CFIm complex",
    "11"="mRNA export",
    "13"="proteosome",
    "9"="mitotic cell cycle",
    "16"="chromatin organization",
    "18"="chaperonin-containing t-complex",
    "15"="cytoplasmic translation",
    "2"="ribosome",
    "12"="ribosome biogenesis",
    "5"="translation initiation",
    "1"="mRNA splicing I",
    "6"="mRNA splicing II",
    "8"="transcription initiation",
    "3"="tRNA activation",
    "7"="DNA replication and repair",
    "4"="transcription initiation and elongation",
    "10"="CPSF, CSTF, and PAF complex",
    "17"="nuclear exosome complex",
    "0"="non-targeting"
)
```


# Data
## Loading
```{r load_data, message=FALSE}
se <- readRDS(FILE_SE)
gr <- read_gff(FILE_GTF, genome_info='hg38') %>%
    filter(type == 'transcript') %>%
    anchor_3p() %>%
    mutate(width=BIN_WIDTH)
df_clusters <- read_csv(FILE_CLUSTERS)

tr_genome <- GenomeAxisTrack(v=10)
```

## Preprocessing
```{r prepare_data}
gene2txs <- rowData(se) %>% 
    as_tibble %>%
    dplyr::select(gene_name, transcript_id) %>%
    group_by(gene_name) %>%
    summarize(txs=list(transcript_id)) %>%
    deframe()

tpm_tx_target <- assay(se, "counts") %>% { 
    idx_ntp <- str_detect(colnames(.), "non-targeting")
    cts_ntp <- rowSums(.[,idx_ntp])
    cts_tx_target <- .[, !idx_ntp]
    cbind(cts_tx_target, "ntp"=cts_ntp)
} %>%
    { . %*% Diagonal(ncol(.), 1e6/colSums(.)) }

M_target_cluster <- df_clusters %>% 
    # dummy entry for NTPs
    add_row(sgID_AB="ntp", cluster_id=0) %>%
    dplyr::select(sgID_AB, cluster_id) %>%
    deframe %>% fac2sparse %>% t

tpm_tx_cluster <- M_target_cluster %>%
    { tpm_tx_target[,rownames(.)] %*% . %*% Diagonal(ncol(.), 1/colSums(.)) }
```

## Functions
```{r methods}
get_gene_gr <- function (gene) {
    filter(gr, transcript_id %in% gene2txs[[gene]])
}

get_counts_gr <- function (gene, cluster) {
    get_gene_gr(gene) %>%
        mutate(score=tpm_tx_cluster[transcript_id, cluster]) %>%
        plyranges::select(score)
}

get_tpm_tr <- function (gene, cluster) {
    DataTrack(get_counts_gr(gene, cluster), name=cluster, genome="hg38",
                    type="hist", width=50)
}

get_tpm_tr_all <- function (gene) {
    lapply(names(LBL_UTR_CLUSTERS), get_tpm_tr, gene=gene)
}

get_gene_tr <- function (gene, chr, start, end) {
    GeneRegionTrack(txdb, chromosome=chr, start=start, end=end, symbol=gene,
                    showId=TRUE, name=gene, geneSymbol=TRUE)
}

harmonize_ylim <- function (trs) {
    max_score <- max(sapply(trs, function (tr) { max(tr@data) }))
    ylims <- c(0, max_score*1.05)
    lapply(trs, function (tr) {
        displayPars(tr) <- list(ylim=ylims)
        tr
    })
}

plot_all_clusters <- function (gene, chr_gene=NULL, start_gene=NULL, end_gene=NULL, GENE_HEIGHT=2) {
    gr_gene <- get_gene_gr(gene)
    if (is.null(chr_gene))   { chr_gene   <- seqnames(gr_gene) %>% as.character %>% `[[`(1) }
    if (is.null(start_gene)) { start_gene <- min(start(gr_gene)) - 1e3 }
    if (is.null(end_gene))   { end_gene   <- max(end(gr_gene)) + 1e3 }
    
    tr_gene <- get_gene_tr(gene, chr_gene, start_gene, end_gene)

    trs_clusters <- get_tpm_tr_all(gene)
    
    plotTracks(append(harmonize_ylim(trs_clusters), list(tr_gene, tr_genome)),
               sizes=c(rep(3, length(LBL_UTR_CLUSTERS)), GENE_HEIGHT, 2),
               from=start_gene, to=end_gene, 
               col.border.title="white",
               fontcolor.title='grey20',
               col.axis="grey20",
               background.title='grey90')
}

save_track_plot <- function (file, gene,
                             chr_gene=NULL, start_gene=NULL, end_gene=NULL, GENE_HEIGHT=2, 
                             PDF_WIDTH=4, PDF_HEIGHT=12) {
    gr_gene <- get_gene_gr(gene)
    if (is.null(chr_gene))   { chr_gene   <- seqnames(gr_gene) %>% as.character %>% `[[`(1) }
    if (is.null(start_gene)) { start_gene <- min(start(gr_gene)) - 1e3 }
    if (is.null(end_gene))   { end_gene   <- max(end(gr_gene)) + 1e3 }
    
    tr_gene <- get_gene_tr(gene, chr_gene, start_gene, end_gene)

    trs_clusters <- get_tpm_tr_all(gene)
    
    pdf(file, width=PDF_WIDTH, height=PDF_HEIGHT)
    plotTracks(append(harmonize_ylim(trs_clusters), list(tr_gene, tr_genome)),
               sizes=c(rep(3, length(LBL_UTR_CLUSTERS)), GENE_HEIGHT, 2),
               from=start_gene, to=end_gene, 
               col.border.title="white",
               fontcolor.title='grey20',
               col.axis="grey20",
               background.title='grey90')
    dev.off()
}
```


# Analysis

## GART
```{r plt_gart, fig.width=4, fig.height=12}
# chr21:33,502,888-33,524,917
GENE="GART"
CHR="chr21"
START=33502888
END=33524917

plot_all_clusters(GENE, CHR, START, END, GENE_HEIGHT=3)
```

### Export
```{r export_gart}
save_track_plot(sprintf("img/gene-plots/kd6-cluster-avg-%s.pdf", tolower(GENE)),
                GENE, CHR, START, END, GENE_HEIGHT=3)
```

## ARF4
```{r plt_arf4, fig.width=4, fig.height=12}
# chr3:57,571,297-57,572,345
GENE="ARF4"
CHR="chr3"
START=57571297
END=57572345

plot_all_clusters(GENE, CHR, START, END, GENE_HEIGHT=3)
```


### Export
```{r export_arf4}
save_track_plot(sprintf("img/gene-plots/kd6-cluster-avg-%s.pdf", tolower(GENE)),
                GENE, CHR, START, END, GENE_HEIGHT=3)
```

## CALM3
```{r plt_calm3, fig.width=4, fig.height=12}
GENE="CALM3"
CHR="chr19"
START=46609000
END=46611000

plot_all_clusters(GENE, CHR, START, END, GENE_HEIGHT=3)
```

### Export
```{r export_calm3}
save_track_plot(sprintf("img/gene-plots/kd6-cluster-avg-%s.pdf", tolower(GENE)),
                GENE, CHR, START, END, GENE_HEIGHT=3)
```

## NIFK
```{r plt_nifk, fig.width=4, fig.height=12}
# chr2:121,726,829-121,727,992
GENE="NIFK"
CHR="chr2"
START=121726829
END=121727992

plot_all_clusters(GENE, CHR, START, END, GENE_HEIGHT=3)
```

### Export
```{r export_nifk}
save_track_plot(sprintf("img/gene-plots/kd6-cluster-avg-%s.pdf", tolower(GENE)),
                GENE, CHR, START, END, GENE_HEIGHT=3)
```

## EIF4A1
```{r plt_eif4a1, fig.width=4, fig.height=12}
# chr17:7,578,444-7,579,047
GENE="EIF4A1"
CHR="chr17"
START=7578444
END=7579047

plot_all_clusters(GENE, CHR, START, END, GENE_HEIGHT=3)
```

### Export
```{r export_eif4a1}
save_track_plot(sprintf("img/gene-plots/kd6-cluster-avg-%s.pdf", tolower(GENE)),
                GENE, CHR, START, END, GENE_HEIGHT=3)
```

## RNF114
```{r plt_rnf114, fig.width=4, fig.height=12}
# chr20:49,951,990-49,954,004
GENE="RNF114"
CHR="chr20"
START=49951990
END=49954004

plot_all_clusters(GENE, CHR, START, END, GENE_HEIGHT=3)
```

### Export
```{r export_rnf114}
save_track_plot(sprintf("img/gene-plots/kd6-cluster-avg-%s.pdf", tolower(GENE)),
                GENE, CHR, START, END, GENE_HEIGHT=3)
```



## TPT1
```{r plt_tpt1, fig.width=4, fig.height=12}
# chr13:45,336,746-45,337,565
GENE="TPT1"
CHR="chr13"
START=45336746
END=45337565

plot_all_clusters(GENE, CHR, START, END, GENE_HEIGHT=3)
```

### Export
```{r export_tpt1}
save_track_plot(sprintf("img/gene-plots/kd6-cluster-avg-%s.pdf", tolower(GENE)),
                GENE, CHR, START, END, GENE_HEIGHT=3)
```


## RPL13A
```{r plt_rpl13a, fig.width=4, fig.height=12}
# chr19:49,491,714-49,492,446
GENE="RPL13A"
CHR="chr19"
START=49491714
END=49492446

plot_all_clusters(GENE, CHR, START, END, GENE_HEIGHT=4)
```

### Export
```{r export_rpl13a}
save_track_plot(sprintf("img/gene-plots/kd6-cluster-avg-%s.pdf", tolower(GENE)),
                GENE, CHR, START, END, GENE_HEIGHT=4)
```


## PRMT2
```{r plt_prmt2, fig.width=4, fig.height=12}
# chr21:46,664,229-46,665,804
GENE="PRMT2"
CHR="chr21"
START=46664229
END=46665804

plot_all_clusters(GENE, CHR, START, END, GENE_HEIGHT=4)
```

### Export
```{r export_prmt2}
save_track_plot(sprintf("img/gene-plots/kd6-cluster-avg-%s.pdf", tolower(GENE)),
                GENE, CHR, START, END, GENE_HEIGHT=4)
```

---

# Runtime Details
## Session Info
```{r sesh_info, echo=FALSE}
sessionInfo()
```

## Conda Environment
```{bash comment="", echo=FALSE}
if ! command -v conda &> /dev/null
then
  echo "Conda not detected."
elif [ -z "${CONDA_PREFIX}" ]
then
  echo "No active Conda environment."
else
  echo "## Conda Environment YAML"
  conda env export
fi
```
