---
title: "Differential Gene Expression Per Cluster - Mann-Whitney"
author: "Mervin M Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float: true
---

# Purpose

Run differential gene expression testing by clusters against non-targeting perturbations.

# Initialization

## Libraries
```{r libs, message=FALSE, warning=FALSE}
library(magrittr)
library(tidyverse)
library(broom)
library(BiocParallel)
```

## Parameters
```{r set_params}
set.seed(20210818)

MIN_TPM=5

FILE_CLUSTERS="tbl/df_target_nnclusters_kd6_essential_ui10.csv"
FILE_TPM="tbl/df_tpm_kd6_essential.Rds"
FILE_WUI="tbl/df_wui_kd6_essential_ui10.Rds"

FILE_OUT="data/dge/df_dge_kd6_clusters.mw_test.tsv.gz"

register(MulticoreParam(8))
```

## Functions

```{r methods}

```

# Data
## Loading
```{r load_data, message=FALSE}
df_targets <- readRDS(FILE_WUI) %>%
    distinct(target_gene, target_gene_id, sgID_AB, n_cells)

df_tpm <- readRDS(FILE_TPM) %>%
    left_join(df_targets, by="sgID_AB")

df_clusters <- read_csv(FILE_CLUSTERS) %>%
    mutate(cluster_id=as.character(cluster_id))

df_ntp <- filter(df_tpm, str_detect(sgID_AB, '^non-targeting')) %>%
    mutate(cluster_id="ntp")

tpm_clusters <- left_join(df_clusters, df_tpm,
                          by=c("target_gene", "target_gene_id", "sgID_AB")) %>%
    split(.$cluster_id)
```

## Preprocessing
```{r prepare_data}
df_tests <- bplapply(tpm_clusters, function (df_cluster) {
    cid <- unique(df_cluster$cluster_id)
    bind_rows(df_ntp, df_cluster) %>%
        group_by(gene_id, gene_name) %>%
        filter(!all(tpm_gene == 0)) %>%
        nest() %>%
        mutate(mean_tpm_ntp=map_dbl(data, ~ mean(.x$tpm_gene[.x$cluster_id == "ntp"])),
               sd_tpm_ntp=map_dbl(data, ~ sd(.x$tpm_gene[.x$cluster_id == "ntp"])),
               mean_tpm_cluster=map_dbl(data, ~ mean(.x$tpm_gene[.x$cluster_id != "ntp"])),
               sd_tpm_cluster=map_dbl(data, ~ sd(.x$tpm_gene[.x$cluster_id != "ntp"])),
               l2fc=log2(mean_tpm_cluster/mean_tpm_ntp)) %>%
        filter((mean_tpm_ntp >= MIN_TPM) | (mean_tpm_cluster >= MIN_TPM)) %>%
        mutate(test=map(data, ~ tidy(wilcox.test(tpm_gene ~ cluster_id, data=.x))),
               data=NULL, cluster_id=cid) %>%
        unnest(test) %>%
        select(-c("method", "alternative")) %>%
        ungroup() %>%
        mutate(p.adj=p.adjust(p.value, method="BH")) %>%
        arrange(p.value)
}) %>% bind_rows()
```

### Export
```{r export_dge}
write_tsv(df_tests, FILE_OUT)
```

# Analysis

## Number of Significant Genes

```{r plt_nsig, fig.width=6, fig.height=4}
df_tests %>%
    group_by(cluster_id) %>%
    summarize(n_sig=sum(p.adj < 0.05), .groups='drop') %>%
    ggplot(aes(x=factor(as.numeric(cluster_id)), y=n_sig)) +
    geom_bar(stat='identity', fill='grey90', color='black') +
    scale_y_continuous(expand=c(0,0,0.05,0)) +
    labs(x="Cluster", y="Number of Significant Genes (FDR < 0.05)") +
    theme_bw()
    
df_tests %>%
    group_by(cluster_id) %>%
    summarize(n_sig=sum(p.adj < 0.05 & abs(l2fc) >= log2(1.5)), .groups='drop') %>%
    ggplot(aes(x=factor(as.numeric(cluster_id)), y=n_sig)) +
    geom_bar(stat='identity', fill='grey90', color='black') +
    scale_y_continuous(expand=c(0,0,0.05,0)) +
    labs(x="Cluster", y="Number of Significant Genes (FDR < 0.05, FC > 1.5)") +
    theme_bw()
    
df_tests %>%
    group_by(cluster_id) %>%
    summarize(n_sig=sum(p.adj < 0.05 & abs(l2fc) >= log2(2)), .groups='drop') %>%
    ggplot(aes(x=factor(as.numeric(cluster_id)), y=n_sig)) +
    geom_bar(stat='identity', fill='grey90', color='black') +
    scale_y_continuous(expand=c(0,0,0.05,0)) +
    labs(x="Cluster", y="Number of Significant Genes (FDR < 0.05, FC > 2)") +
    theme_bw()
```

# Conclusion

<!--
What was found?
Clearly state conclusions.
Was there anything unexpected?
Are there unanswered questions?
What should be worked on next?
-->

---

# Runtime Details
## Session Info
```{r sesh_info, echo=FALSE}
sessionInfo()
```

## Conda Environment
```{bash comment="", echo=FALSE}
if ! command -v conda &> /dev/null
then
  echo "Conda not detected."
elif [ -z "${CONDA_PREFIX}" ]
then
  echo "No active Conda environment."
else
  echo "## Conda Environment YAML"
  conda env export
fi
```
