---
title: "Filter KD8 Genome-Wide Perturb-Seq scUTRquant Data"
author: "Mervin M Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float: true
---

# Purpose

Counts from scUTRquant include all cells passing the UMI threshold. We will filter
to only those cells annotated in the published data.

# Initialization

## Libraries
```{r libs, message=FALSE, warning=FALSE}
library(magrittr)
library(HDF5Array)
library(SingleCellExperiment)
```

## Parameters
```{r set_params}
set.seed(20210818)
invisible(DelayedArray:::set_verbose_block_processing(TRUE))
DelayedArray::setAutoBlockSize(1e9)
DIR_SCE = "data/sce"
FILES_SCE = c(FILE_SCE_TX1="kd8_gwps_p1.txs.",
              FILE_SCE_TX2="kd8_gwps_p2.txs.",
              FILE_SCE_TX3="kd8_gwps_p3.txs.")

OUT_SCE_TX = "kd8_gwps.annot.txs."
```

## Functions
```{r functions}
load_filtered_sce <- function (file_sce) {
    loadHDF5SummarizedExperiment(DIR_SCE, file_sce) %>%
        `[`(, !is.na(.$gem_group))
}
```


# Data
## Transcripts
```{r load_txs, message=FALSE}
sce_txs <- lapply(FILES_SCE, load_filtered_sce) %>% do.call(what=cbind)
```

### Export
```{r export_txs}
chunkdim <- c(dim(sce_txs)[[1]], 1e4L)
saveHDF5SummarizedExperiment(sce_txs[,seq(3e4)], DIR_SCE, OUT_SCE_TX, 
                             chunkdim=chunkdim, level=1L, verbose=TRUE)#, as.sparse=TRUE)
```


---

# Runtime Details
## Session Info
```{r sesh_info, echo=FALSE}
sessionInfo()
```

## Conda Environment
```{bash comment="", echo=FALSE}
if ! command -v conda &> /dev/null
then
  echo "Conda not detected."
elif [ -z "${CONDA_PREFIX}" ]
then
  echo "No active Conda environment."
else
  echo "## Conda Environment YAML"
  conda env export
fi
```
